
# .streamlit/secrets.toml

private_gsheets_url = 'https://docs.google.com/spreadsheets/d/1Q9A-rSoxYxNRL4smyyaFnNWlRX9Mvp3RmxEhHiipEd8/edit?usp=sharing'

[gcp_service_account]
type= "service_account"
project_id= "condor-app-345720"
private_key_id= "0579014f0ee2bb9bd8096288ea37663a57dd43ad"
private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDcCd5/mft5Uga6\n1iqCY7kCFqqSzsmTSm6wZzbwhw7qaxvKP7E8geZycD80ENTgyBPLKKjhcOfjjRMa\n4qp11vAJ865/xE2r2XMjAw3pTYXm/2bFGjlelUdbgdYZOLxgQWiJC+JO/oaXWaIA\nDdd0E7STdGIhKHw6Vne5P1Ng+dcaq59kJM8JiMMHApF59H4CjIMKwe962sG4xhK9\n/4fVVTii7/agCGx3kAI2vgcVFo8whM4zuRkx15MkEYI0bD8Rh22W+G4C8/P0HtHz\ninmjwG6seoPrPrnsrJtvFz2GTSc6ocEyDBEKUHNOlrSbDFNuzWNMS1T6qtxwDMFK\n5Y65RUFTAgMBAAECgf83AkCdpeE4c0k7bE80Sbn2y7PY/9lk+Tay4xrZBuqzsBNC\nfKnSdqcl9OnYGl0d1Ocd4wxVT+So/pvIHOKAkztvQXxedLT2QWaHWjwgF0Fifncy\nz1uIScmNFuhvZb+yUKfRmyb4mKkNLVtSqCM04bhDJNVjdLuZ2gQUS8CMfelIwShM\nEhtMo6XnVgqRG6TXEJl7sAis2M3grW2bLvDPzaO/el/EJu3pUI4UR2m8Z48EXWi6\nkO3iDyvSWO2IPPt24BOAYY4/akOz/cw7skddZSzq0P3i2Fbb6HHtYMKAfTFQEK6g\nzNv26LnDS1a+9i+ZqDQJSDcJnTVfdkNkOsfSnAECgYEA+I5gpxWlzrFCErohgZdL\nWwuhoJbEaObbAvO0uvXM+iClWiNhDPe86rtZCVs9RCpIiFXqH3oGqifgCY2udON0\ngG4Zt/5Cb/4P/nQ540c3EiRK96naTLGG9lGOzQbxJrNzfUu1mJ6msOnZoDNmI0dp\nwqImZGfs1iQhza5UciHrrwsCgYEA4qDainjnKinQtyM6JKBrZc36PXCQbev91qfY\nnOSOcE3SH4KMlz7ZOegPBaqUHVaKkX3oV+vcsXYeeSITu16kw6cKe4DPd30I0plW\nih3XM0g36XILhmoobcY9sPpdOVImSSBohVyW/7SorD5ydegEaeQz70ttClk8aDKY\nbGHKQ9kCgYEApT16MfopRdT/+RU2y0F6vmdoJyu0HY1EEp1UDGr2v17OrrMQhR95\nv4+XbKn0fAmkOMbtI8nq/loODivbzCeevvbzMCffoTaFCYPZLCifCveHw0hvMUdg\nUwb7aYBw92qbn7OiYXkvljORE3i4MUH7pIJKBbw1blONCYEY8NtuJOsCgYEA0fUM\nArW4FAvhXYm5WC120j5d04XxiKTV6oRd3hyxCcJPJPohng2P2mHvaOR7jCKdBeWL\n18igEZjI6phzh2dLZiffQkQ38Q9ZmSKOVi8HLG9/vTr3CnRXODws80VAENbWuXDY\n5JS/H+8TRWAlUq69SA0vQEa0op3BpRcat25xoSECgYEAlqBhGs/pnVOukF0GtWWu\nR1IdcQpLxw+ZgAcDURNZ98u08xjhyxvg0a196SpHM0LFql9o5WsTxCzOMRSuwrd1\nwEY1lxCbbVRnqBiECEkip/BMlHWeMNIgqRnegK3JeB2S42QLaam6GOqWqpcs/lU7\nTm6lsQ49mGR044m5H5e7zzE=\n-----END PRIVATE KEY-----\n"
client_email= "condor-app@condor-app-345720.iam.gserviceaccount.com"
client_id= "116934082346221795770"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/condor-app%40condor-app-345720.iam.gserviceaccount.com"


[passwords]
# Follow the rule: username = "password"
david = "123"

[passwords2]
# Follow the rule: username = "password"
carvalho = "1234"

[passwords3]
# Follow the rule: username = "password"
siqueira = "12345"